name: Publish to GitHub Container Registry

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - master
      - dev

jobs:
  publish_ghcr_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install qemu (required for cross-platform builds)
        run: |
          sudo apt update
          sudo apt -y install qemu-system qemu-user-static
          sudo systemctl restart docker

      - name: Create multiplatform docker builder
        run: docker buildx create --use

      - name: Sanitize repo owner
        uses: actions/github-script@v4
        id: repo_slug
        with:
          result-encoding: string
          script: return '${{ github.repository_owner }}'.toLowerCase()

      - name: Build and publish images to GHCR
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASS: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_IMAGE: ghcr.io/${{ steps.repo_slug.outputs.result }}/avalanchego
          BUILD_MULTI_ARCH: 1
        run: scripts/build_image.sh

      - name: Build and publish bootstrap-monitor image to GHCR
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASS: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_IMAGE: ghcr.io/${{ steps.repo_slug.outputs.result }}-bootstrap-monitor
          BUILD_MULTI_ARCH: 1
        run: scripts/build_bootstrap_monitor_image.sh
